export const KEYS = [
	{value: 'C Major', label: 'C Major'},
	{value: 'G Major', label: 'G Major'},
	{value: 'D Major', label: 'D Major'},
	{value: 'A Major', label: 'A Major'},
	{value: 'E Major', label: 'E Major'},
	{value: 'B Major', label: 'B Major'},
	{value: 'F Sharp Major', label: 'F# Major'},
	{value: 'C Sharp Major', label: 'C# Major'},
	{value: 'F Major', label: 'F Major'},
	{value: 'B Flat Major', label: 'Bb Major'},
	{value: 'E Flat Major', label: 'Eb Major'},
	{value: 'A Flat Major', label: 'Ab Major'},
	{value: 'D Flat Major', label: 'Db Major'},
	{value: 'G Flat Major', label: 'Gb Major'},
	{value: 'C Flat Major', label: 'Cb Major'},
	{value: 'A Minor', label: 'A Minor'},
	{value: 'E Minor', label: 'E Minor'},
	{value: 'B Minor', label: 'B Minor'},
	{value: 'F Sharp Minor', label: 'F# Minor'},
	{value: 'C Sharp Minor', label: 'C# Minor'},
	{value: 'G Sharp Minor', label: 'G# Minor'},
	{value: 'D Sharp Minor', label: 'D# Minor'},
	{value: 'A Sharp Minor', label: 'A# Minor'},
	{value: 'D Minor', label: 'D Minor'},
	{value: 'G Minor', label: 'G Minor'},
	{value: 'C Minor', label: 'C Minor'},
	{value: 'F Minor', label: 'F Minor'},
	{value: 'B Flat Minor', label: 'Bb Minor'},
	{value: 'E Flat Minor', label: 'Eb Minor'},
	{value: 'A Flat Minor', label: 'Ab Minor'},
];
export const BG_COLOR_CLASSES = [
	'bg-blue-500',
	'bg-teal-500',
	'bg-yellow-500',
	'bg-orange-500',
	'bg-green-500',
	'bg-lime-500',
	'bg-red-500',
	'bg-pink-500',
	'bg-purple-500',
	'bg-indigo-500',
	'bg-cyan-500',
	'bg-emerald-500',
	'bg-gray-500',
	'bg-gray-900',
];
export const FILL_COLOR_CLASSES = [
	'fill-blue-500',
	'fill-teal-500',
	'fill-yellow-500',
	'fill-orange-500',
	'fill-green-500',
	'fill-lime-500',
	'fill-red-500',
	'fill-pink-500',
	'fill-purple-500',
	'fill-indigo-500',
	'fill-cyan-500',
	'fill-emerald-500',
	'fill-gray-500',
	'fill-gray-900',
];
